version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:senha123@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - app-network   
  
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000   
    depends_on:
      - backend
    networks:
      - app-network   

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senha123
    command: mongod --auth
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=senha123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:senha123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=senha123
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network
    
volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge